# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  branches:
    include:
    - master
    - rls/*

pr:
  branches:
    include:
    - master
    - rls/*

jobs:
- job: 'ClangFormat'
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
    - script: |
        .ci/env/clang.sh
      displayName: 'apt-get'
    - script: |
        .ci/scripts/clang-format.sh
      displayName: 'clang-format check'
      failOnStderr: true

- job: 'Copilotscan'
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
    - script: bash <(curl -s https://copilot.blackducksoftware.com/ci/azure/scripts/upload)
      displayName: 'Copilot scan'

-
#- job: Windows
#  timeoutInMinutes: 0
#  pool:
#    vmImage: 'windows-2019'
#  steps:
#  - script: |
#      java -version
#      set INCLUDE=%JAVA_HOME%\include;%INCLUDE%
#      echo "call .ci\env\tbb.bat"
#      call .ci\env\tbb.bat
#      echo "call .\dev\download_micromkl.bat"
#      call .\dev\download_micromkl.bat
#      echo call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall" x64
#      call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall" x64
#      echo make daal COMPILER=vc PLAT="win32e" REQCPU="avx2"
#      make daal COMPILER=vc PLAT="win32e" REQCPU="avx2"
#    displayName: 'Build'
