name: docker-validation Nightly

on:
  schedule:
    - cron: "0 23 * * *"
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/docker-validation-nightly.yml
      - dev/docker/onedal-dev.Dockerfile
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker-validation-nightly.yml
      - dev/docker/onedal-dev.Dockerfile

jobs:
  validate:
    name: Docker validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Build docker image
        run: docker build . --file dev/docker/onedal-dev.Dockerfile --build-arg config=build_make --tag onedal-dev:$(date +%s)
