name: docker-validation CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  validate:
    name: Docker validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Build docker image
        run: docker build . --file dev/docker/onedal-dev.Dockerfile --tag onedal-dev:latest
