name: docker-validation Nightly

on:
  schedule:
    - cron: "0 23 * * *"
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/docker-validation-nightly.yml
      - dev/docker/onedal-dev.Dockerfile
      - .ci/env
      - .ci/scripts
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker-validation-nightly.yml
      - dev/docker/onedal-dev.Dockerfile
      - .ci/env
      - .ci/scripts

jobs:
  validate:
    name: Docker validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Build docker image
        run: docker build . --file dev/docker/onedal-dev.Dockerfile --tag onedal-dev:latest
      - name: Building DAAL
        run: docker run onedal-dev .ci/scripts/build.sh --compiler gnu --optimizations avx2 --target daal --conda-env ci-env
      - name: Building oneDAL
        run: .ci/scripts/build.sh --compiler gnu --optimizations avx2 --target oneapi_c
      - name: Building oneDAL with bazel
        run: bazel build :release
